#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.


################################################################################
# Edit the following constants and then rename this script to ~/.xmonad/build

# The directory holding your source code and stack.yaml file:
SRC_DIR=$HOME/.config/xmonad

# The name of the executable produced by stack.  This comes from the
# executable section of your *.cabal or package.yaml file.
EXE_NAME=xmonad
EXE_XMOBAR=xmobar

################################################################################



# Unset STACK_YAML, to ensure that $SRC_DIR/stack.yaml is used.
unset STACK_YAML
FAIL=0

# Do the build
cd $SRC_DIR

stack build 2>.log || FAIL=1

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T $(stack exec -- which $EXE_NAME) $1 2>.log || FAIL=2
exit $FAIL
