name: my-xmonad
version: 0.1.0.0

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -threaded -with-rtsopts=-V0

dependencies:
  - base
  - containers
  - data-default
  - directory
  - filepath
  - fuzzy
  - hostname
  - monoid-subclasses
  - mtl
  - process
  - regex-tdfa
  - utf8-string
  - unix
  - X11
  - xmobar
  - xmonad >= 0.18
  - xmonad-contrib >= 0.18


executables:
  xmonad:
    main: xmonad.hs
    source-dirs:
      - lib/src
      - .
    language: GHC2021
    dependencies:
      - xmonad
      - X11 
  xmobar:
    main: xmobar.hs
    language: GHC2021
    dependencies:
      - xmobar
      - extra

# library:
#   source-dirs:
#     - lib
#     - .
#   exposed-modules:
#     - XMonad.Actions.CycleRecentWS