#!/bin/sh

~paul/.config/xmonad/xmonad-session-rc &
if [ -e ~paul/.cache/xmonad/xmonad-x86_64-linux ] ; then
    exec ~paul/.cache/xmonad/xmonad-x86_64-linux "$@"
else
    exec ~paul/.local/bin/xmonad "$@"
fi
